module.exports = {
  apps: [
    {
      name: "ip-copilot",
      cwd: "/opt/chuangshizhe-copilot/apps/ip-copilot",
      script: "npx",
      args: "next start",
      env: {
        NODE_ENV: "production",
        PORT: "3000",
        HOSTNAME: "0.0.0.0",
        DATABASE_URL: "postgresql://chuangshizhe_user:Csj2026Secure!@111.228.45.216:5432/chuangshizhe",
        ALIYUN_API_KEY: "sk-sp-1fc4713d28464b50b8192309019f279c",
        OPENCLAW_API_URL: "http://127.0.0.1:18789",
        OPENCLAW_API_KEY: "exb65abpkt72xenkzjsfectwmrmjes33",
        HERMES_API_URL: "http://127.0.0.1:9119",
      },
      instances: 1,
      autorestart: true,
      max_memory_restart: "1G",
      error_file: "/var/log/pm2/ip-copilot-error.log",
      out_file: "/var/log/pm2/ip-copilot-out.log",
      merge_logs: true,
    },
    {
      name: "admin",
      cwd: "/opt/chuangshizhe-copilot/apps/admin",
      script: "npx",
      args: "next start",
      env: {
        NODE_ENV: "production",
        PORT: "3002",
        HOSTNAME: "0.0.0.0",
        DATABASE_URL: "postgresql://chuangshizhe_user:Csj2026Secure!@111.228.45.216:5432/chuangshizhe",
      },
      instances: 1,
      autorestart: true,
      max_memory_restart: "1G",
      error_file: "/var/log/pm2/admin-error.log",
      out_file: "/var/log/pm2/admin-out.log",
      merge_logs: true,
    },
  ],
};
